#!/bin/bash
# Different durations to test, as the SG2000 takes 12 hours for a single image
echo '----------------[start]------------------
positive_prompt: a photo of an astronaut riding a horse on mars
negative_prompt: ugly, blurry
output_png_path: ./result.png
steps: 10
seed: 265216
----------------[prompt]------------------
Token: "a</w>"
Token: "photo</w>"
Token: "of</w>"
Token: "an</w>"
Token: "astronaut</w>"
Token: "riding</w>"
Token: "a</w>"
Token: "horse</w>"
Token: "on</w>"
Token: "mars</w>"
Token: "ugly</w>"
Token: ",</w>"
Token: "blurry</w>"
----------------[diffusion]---------------
step:0          3.8681e+06ms
step:1          3.86243e+06ms
step:2          3.88526e+06ms
step:3          3.86185e+06ms
step:4          3.8616e+06ms
step:5          512072ms
step:6          508252ms
step:7          507357ms
step:8          516970ms
step:9          512945ms
----------------[decode]------------------
----------------[save]--------------------
----------------[close]-------------------'
